const DIMENSIONS = ["loyalty", "courage", "wisdom", "righteousness", "freedom", "charisma"];

const CHARACTERS = [
  { id: "song_jiang", name: "宋江", nickname: "及时雨", archetype: "忠义凝聚型领导", tags: ["忠义", "凝聚", "宽厚"], scores: { loyalty: 92, courage: 30, wisdom: 55, righteousness: 65, freedom: 15, charisma: 90 } },
  { id: "lu_junyi", name: "卢俊义", nickname: "玉麒麟", archetype: "英武忠厚型统帅", tags: ["英武", "忠厚", "名声"], scores: { loyalty: 70, courage: 75, wisdom: 35, righteousness: 70, freedom: 20, charisma: 55 } },
  { id: "wu_yong", name: "吴用", nickname: "智多星", archetype: "智谋型军师", tags: ["智谋", "筹策", "权变"], scores: { loyalty: 50, courage: 20, wisdom: 95, righteousness: 30, freedom: 25, charisma: 40 } },
  { id: "gongsun_sheng", name: "公孙胜", nickname: "入云龙", archetype: "超脱淡泊型隐士", tags: ["超脱", "淡泊", "灵慧"], scores: { loyalty: 30, courage: 40, wisdom: 88, righteousness: 45, freedom: 95, charisma: 25 } },
  { id: "guan_sheng", name: "关胜", nickname: "大刀", archetype: "威严正统型猛将", tags: ["威严", "正统", "忠烈"], scores: { loyalty: 88, courage: 78, wisdom: 30, righteousness: 88, freedom: 10, charisma: 48 } },
  { id: "lin_chong", name: "林冲", nickname: "豹子头", archetype: "隐忍刚烈型武将", tags: ["隐忍", "刚烈", "正道"], scores: { loyalty: 55, courage: 72, wisdom: 38, righteousness: 80, freedom: 15, charisma: 32 } },
  { id: "qin_ming", name: "秦明", nickname: "霹雳火", archetype: "刚烈暴躁型先锋", tags: ["暴烈", "果决", "先锋"], scores: { loyalty: 65, courage: 95, wisdom: 10, righteousness: 45, freedom: 45, charisma: 35 } },
  { id: "hua_rong", name: "花荣", nickname: "小李广", archetype: "忠诚优雅型将领", tags: ["忠诚", "优雅", "精准"], scores: { loyalty: 95, courage: 65, wisdom: 45, righteousness: 75, freedom: 25, charisma: 50 } },
  { id: "chai_jin", name: "柴进", nickname: "小旋风", archetype: "仗义疏财型贵族", tags: ["仗义", "疏财", "礼贤"], scores: { loyalty: 50, courage: 25, wisdom: 50, righteousness: 60, freedom: 55, charisma: 75 } },
  { id: "lu_zhishen", name: "鲁智深", nickname: "花和尚", archetype: "豪爽正义型好汉", tags: ["豪爽", "正义", "慈悲"], scores: { loyalty: 72, courage: 90, wisdom: 40, righteousness: 95, freedom: 80, charisma: 65 } },
  { id: "wu_song", name: "武松", nickname: "行者", archetype: "刚烈果敢型英雄", tags: ["刚烈", "果敢", "嫉恶"], scores: { loyalty: 60, courage: 98, wisdom: 30, righteousness: 85, freedom: 65, charisma: 48 } },
  { id: "dong_ping", name: "董平", nickname: "双枪将", archetype: "野心果决型将领", tags: ["果决", "野心", "灵活"], scores: { loyalty: 25, courage: 85, wisdom: 55, righteousness: 20, freedom: 60, charisma: 65 } },
  { id: "yang_zhi", name: "杨志", nickname: "青面兽", archetype: "志高运蹇型英雄", tags: ["志高", "刚直", "不甘"], scores: { loyalty: 45, courage: 72, wisdom: 30, righteousness: 55, freedom: 18, charisma: 28 } },
  { id: "dai_zong", name: "戴宗", nickname: "神行太保", archetype: "机敏务实型执行者", tags: ["机敏", "务实", "快速"], scores: { loyalty: 60, courage: 45, wisdom: 58, righteousness: 45, freedom: 40, charisma: 38 } },
  { id: "li_kui", name: "李逵", nickname: "黑旋风", archetype: "粗犷直率型猛将", tags: ["粗犷", "直率", "冲动"], scores: { loyalty: 90, courage: 100, wisdom: 5, righteousness: 40, freedom: 75, charisma: 40 } },
  { id: "shi_jin", name: "史进", nickname: "九纹龙", archetype: "热血少年型好汉", tags: ["热血", "少年", "单纯"], scores: { loyalty: 65, courage: 82, wisdom: 18, righteousness: 50, freedom: 68, charisma: 35 } },
  { id: "shi_xiu", name: "石秀", nickname: "拼命三郎", archetype: "精明果敢型行动者", tags: ["精明", "果敢", "敏锐"], scores: { loyalty: 62, courage: 88, wisdom: 65, righteousness: 48, freedom: 45, charisma: 30 } },
  { id: "yan_qing", name: "燕青", nickname: "浪子", archetype: "聪慧灵动型浪子", tags: ["聪慧", "灵动", "多才"], scores: { loyalty: 80, courage: 50, wisdom: 82, righteousness: 50, freedom: 75, charisma: 78 } },
  { id: "zhang_shun", name: "张顺", nickname: "浪里白条", archetype: "水上豪杰型义士", tags: ["勇猛", "义气", "信义"], scores: { loyalty: 80, courage: 85, wisdom: 28, righteousness: 68, freedom: 50, charisma: 40 } },
  { id: "ruan_xiaoqi", name: "阮小七", nickname: "活阎罗", archetype: "豪放不羁型渔民", tags: ["豪放", "不羁", "自在"], scores: { loyalty: 50, courage: 85, wisdom: 20, righteousness: 35, freedom: 95, charisma: 32 } },
  { id: "zhu_tong", name: "朱仝", nickname: "美髯公", archetype: "仁义温和型义士", tags: ["仁义", "温和", "体面"], scores: { loyalty: 88, courage: 55, wisdom: 40, righteousness: 80, freedom: 30, charisma: 55 } },
  { id: "li_jun", name: "李俊", nickname: "混江龙", archetype: "自主独立型水上首领", tags: ["自主", "独立", "远见"], scores: { loyalty: 40, courage: 75, wisdom: 65, righteousness: 40, freedom: 85, charisma: 60 } },
  { id: "lei_heng", name: "雷横", nickname: "插翅虎", archetype: "正直勇猛型都头", tags: ["正直", "勇猛", "讲理"], scores: { loyalty: 80, courage: 72, wisdom: 28, righteousness: 75, freedom: 25, charisma: 35 } },
  { id: "shi_qian", name: "时迁", nickname: "鼓上蚤", archetype: "灵活机巧型奇才", tags: ["灵活", "机巧", "非常规"], scores: { loyalty: 40, courage: 40, wisdom: 60, righteousness: 25, freedom: 82, charisma: 25 } },
];

const QUESTIONS = [
  { id: "q01", text: "如果你生在梁山时代，你最可能因为什么上山？",
    options: [
      { key: "A", text: "被人陷害，走投无路", weights: { loyalty: 1, courage: -1, wisdom: 0, righteousness: 3, freedom: -2, charisma: -1 } },
      { key: "B", text: "主动投奔，寻找志同道合的人", weights: { loyalty: 2, courage: 1, wisdom: 0, righteousness: 0, freedom: 1, charisma: 3 } },
      { key: "C", text: "犯了事，需要避风头", weights: { loyalty: -2, courage: 1, wisdom: -1, righteousness: -2, freedom: 3, charisma: 0 } },
      { key: "D", text: "被朋友拉去的，义气使然", weights: { loyalty: 4, courage: 0, wisdom: -1, righteousness: 1, freedom: -2, charisma: 2 } },
    ],
  },
  { id: "q02", text: "你更认同哪种活法？",
    options: [
      { key: "A", text: "宁可站着死，不愿跪着生", weights: { loyalty: 0, courage: 3, wisdom: -2, righteousness: 4, freedom: 2, charisma: -1 } },
      { key: "B", text: "留得青山在，不怕没柴烧", weights: { loyalty: 0, courage: -2, wisdom: 3, righteousness: 0, freedom: 1, charisma: 0 } },
      { key: "C", text: "一人得道，鸡犬升天", weights: { loyalty: 1, courage: 0, wisdom: 1, righteousness: -2, freedom: 0, charisma: 4 } },
      { key: "D", text: "逍遥自在，不问世事", weights: { loyalty: -3, courage: 0, wisdom: 1, righteousness: -1, freedom: 4, charisma: -1 } },
    ],
  },
  { id: "q03", text: "面对一个明显不公的上级，你会？",
    options: [
      { key: "A", text: "忍着，等机会再收拾他", weights: { loyalty: -1, courage: -2, wisdom: 3, righteousness: 0, freedom: -1, charisma: 0 } },
      { key: "B", text: "当面顶撞，大不了不干了", weights: { loyalty: -1, courage: 4, wisdom: -2, righteousness: 2, freedom: 3, charisma: 0 } },
      { key: "C", text: "联合其他人一起对抗", weights: { loyalty: 1, courage: 1, wisdom: 1, righteousness: 1, freedom: -2, charisma: 3 } },
      { key: "D", text: "离开这个环境，另寻出路", weights: { loyalty: -2, courage: 1, wisdom: 2, righteousness: 0, freedom: 4, charisma: -1 } },
    ],
  },
  { id: "q04", text: "你认为人生最大的成就是什么？",
    options: [
      { key: "A", text: "留下一世清名", weights: { loyalty: 1, courage: -1, wisdom: 0, righteousness: 4, freedom: -2, charisma: 2 } },
      { key: "B", text: "干一番轰轰烈烈的事", weights: { loyalty: 0, courage: 4, wisdom: -1, righteousness: 1, freedom: 1, charisma: 2 } },
      { key: "C", text: "身边有一帮生死兄弟", weights: { loyalty: 4, courage: 0, wisdom: -1, righteousness: 1, freedom: -2, charisma: 3 } },
      { key: "D", text: "活得自在痛快", weights: { loyalty: -2, courage: 1, wisdom: 0, righteousness: -1, freedom: 4, charisma: 0 } },
    ],
  },
  { id: "q05", text: "如果有人欺骗了你的信任，你会？",
    options: [
      { key: "A", text: "一刀两断，老死不相往来", weights: { loyalty: -3, courage: 2, wisdom: 0, righteousness: 3, freedom: 1, charisma: -1 } },
      { key: "B", text: "记在心里，日后找机会讨回", weights: { loyalty: -1, courage: 1, wisdom: 3, righteousness: 0, freedom: 0, charisma: -1 } },
      { key: "C", text: "看情况，也许会原谅一次", weights: { loyalty: 2, courage: -1, wisdom: 1, righteousness: -1, freedom: 0, charisma: 2 } },
      { key: "D", text: "无所谓，反正也没指望谁", weights: { loyalty: -3, courage: 0, wisdom: 0, righteousness: -1, freedom: 4, charisma: -2 } },
    ],
  },
  { id: "q06", text: "你更怕哪种局面？",
    options: [
      { key: "A", text: "被人误解，百口莫辩", weights: { loyalty: 2, courage: -1, wisdom: 0, righteousness: 0, freedom: -2, charisma: 3 } },
      { key: "B", text: "孤身一人，无依无靠", weights: { loyalty: 3, courage: -1, wisdom: 0, righteousness: 0, freedom: -2, charisma: 3 } },
      { key: "C", text: "被人控制，没有自由", weights: { loyalty: -1, courage: 1, wisdom: 0, righteousness: 0, freedom: 4, charisma: -1 } },
      { key: "D", text: "明知该出手却不敢出手", weights: { loyalty: 0, courage: 4, wisdom: -1, righteousness: 2, freedom: 0, charisma: -1 } },
    ],
  },
  { id: "q07", text: "你觉得什么样的人最值得敬佩？",
    options: [
      { key: "A", text: "宁折不弯的人", weights: { loyalty: 0, courage: 3, wisdom: -1, righteousness: 4, freedom: 1, charisma: 0 } },
      { key: "B", text: "深谋远虑的人", weights: { loyalty: -1, courage: -2, wisdom: 4, righteousness: 0, freedom: 1, charisma: 0 } },
      { key: "C", text: "重情重义的人", weights: { loyalty: 4, courage: 0, wisdom: -1, righteousness: 2, freedom: -2, charisma: 2 } },
      { key: "D", text: "活得洒脱的人", weights: { loyalty: -2, courage: 1, wisdom: 0, righteousness: -1, freedom: 4, charisma: 0 } },
    ],
  },
  { id: "q08", text: "遇到棘手的问题，你习惯怎么处理？",
    options: [
      { key: "A", text: "先调查清楚，再想办法", weights: { loyalty: 0, courage: -2, wisdom: 4, righteousness: 0, freedom: -1, charisma: 0 } },
      { key: "B", text: "边做边想，在实践中摸索", weights: { loyalty: 0, courage: 2, wisdom: -1, righteousness: 0, freedom: 3, charisma: 0 } },
      { key: "C", text: "找靠谱的人一起商量", weights: { loyalty: 2, courage: -1, wisdom: 1, righteousness: 0, freedom: -2, charisma: 3 } },
      { key: "D", text: "想好了就干，不犹豫", weights: { loyalty: 0, courage: 4, wisdom: -1, righteousness: 1, freedom: 2, charisma: -1 } },
    ],
  },
  { id: "q09", text: "你做决定时更依赖什么？",
    options: [
      { key: "A", text: "直觉和胆量", weights: { loyalty: -1, courage: 4, wisdom: -3, righteousness: 0, freedom: 2, charisma: 0 } },
      { key: "B", text: "分析和推理", weights: { loyalty: 0, courage: -2, wisdom: 4, righteousness: 1, freedom: 0, charisma: 0 } },
      { key: "C", text: "身边人的意见", weights: { loyalty: 3, courage: -1, wisdom: -1, righteousness: 0, freedom: -3, charisma: 3 } },
      { key: "D", text: "心里的原则", weights: { loyalty: 1, courage: 1, wisdom: -1, righteousness: 4, freedom: 0, charisma: -1 } },
    ],
  },
  { id: "q10", text: "有人得罪了你，你会？",
    options: [
      { key: "A", text: "当场发作，不藏着掖着", weights: { loyalty: 0, courage: 4, wisdom: -3, righteousness: 1, freedom: 2, charisma: -1 } },
      { key: "B", text: "先忍着，找机会再算账", weights: { loyalty: -1, courage: -1, wisdom: 4, righteousness: 0, freedom: 0, charisma: 0 } },
      { key: "C", text: "看情况，能过就过", weights: { loyalty: 0, courage: -1, wisdom: 1, righteousness: -1, freedom: 2, charisma: 1 } },
      { key: "D", text: "直接翻脸，恩断义绝", weights: { loyalty: -3, courage: 2, wisdom: -1, righteousness: 3, freedom: 2, charisma: -2 } },
    ],
  },
  { id: "q11", text: "你觉得什么是真正的聪明？",
    options: [
      { key: "A", text: "看透局势，总能走在前面", weights: { loyalty: -1, courage: 0, wisdom: 4, righteousness: 0, freedom: 2, charisma: 0 } },
      { key: "B", text: "知道什么时候该出手", weights: { loyalty: 0, courage: 2, wisdom: 3, righteousness: 0, freedom: 0, charisma: 0 } },
      { key: "C", text: "让别人愿意跟着你干", weights: { loyalty: 1, courage: 0, wisdom: -1, righteousness: -1, freedom: -2, charisma: 4 } },
      { key: "D", text: "明白自己要什么，不被左右", weights: { loyalty: -2, courage: 0, wisdom: 2, righteousness: 0, freedom: 4, charisma: -1 } },
    ],
  },
  { id: "q12", text: "如果朋友拉你去做一件有风险的事，你会？",
    options: [
      { key: "A", text: "只要信得过这个人，就去", weights: { loyalty: 4, courage: 1, wisdom: -3, righteousness: 0, freedom: 0, charisma: 1 } },
      { key: "B", text: "先问清楚值不值得冒险", weights: { loyalty: -1, courage: -1, wisdom: 4, righteousness: 1, freedom: 0, charisma: 0 } },
      { key: "C", text: "看有没有把握，再决定", weights: { loyalty: 0, courage: -1, wisdom: 3, righteousness: 0, freedom: 1, charisma: 0 } },
      { key: "D", text: "去，人生就是要折腾", weights: { loyalty: -1, courage: 4, wisdom: -2, righteousness: 0, freedom: 3, charisma: 0 } },
    ],
  },
  { id: "q13", text: "你交朋友最看重什么？",
    options: [
      { key: "A", text: "能不能一起扛事", weights: { loyalty: 4, courage: 1, wisdom: -1, righteousness: 1, freedom: -2, charisma: 0 } },
      { key: "B", text: "能不能聊到一起", weights: { loyalty: 0, courage: 0, wisdom: 0, righteousness: -1, freedom: 3, charisma: 2 } },
      { key: "C", text: "人靠不靠谱", weights: { loyalty: 2, courage: -1, wisdom: 1, righteousness: 3, freedom: -1, charisma: 0 } },
      { key: "D", text: "有没有本事", weights: { loyalty: -1, courage: 0, wisdom: 2, righteousness: -1, freedom: 1, charisma: 3 } },
    ],
  },
  { id: "q14", text: "在一个群体里，你通常是？",
    options: [
      { key: "A", text: "牵头的人，带着大家干", weights: { loyalty: 0, courage: 1, wisdom: -1, righteousness: 0, freedom: -1, charisma: 4 } },
      { key: "B", text: "出主意的人，帮着想办法", weights: { loyalty: 0, courage: -2, wisdom: 4, righteousness: 0, freedom: 2, charisma: 0 } },
      { key: "C", text: "干实事的人，冲锋在前", weights: { loyalty: 1, courage: 4, wisdom: -1, righteousness: 1, freedom: 0, charisma: -1 } },
      { key: "D", text: "不太掺和，保持距离", weights: { loyalty: -2, courage: -1, wisdom: 1, righteousness: -1, freedom: 4, charisma: -2 } },
    ],
  },
  { id: "q15", text: "如果朋友被欺负了，你会？",
    options: [
      { key: "A", text: "二话不说，替他出头", weights: { loyalty: 3, courage: 4, wisdom: -3, righteousness: 2, freedom: 0, charisma: 0 } },
      { key: "B", text: "问清楚原因，再想办法", weights: { loyalty: 1, courage: -1, wisdom: 4, righteousness: 0, freedom: 0, charisma: 0 } },
      { key: "C", text: "帮他出气，但不希望闹大", weights: { loyalty: 2, courage: 0, wisdom: 1, righteousness: 0, freedom: -1, charisma: 2 } },
      { key: "D", text: "让他自己解决，这是他的事", weights: { loyalty: -3, courage: -1, wisdom: 0, righteousness: -1, freedom: 4, charisma: -2 } },
    ],
  },
  { id: "q16", text: "你和别人意见不一致时，你会？",
    options: [
      { key: "A", text: "坚持自己的，不轻易妥协", weights: { loyalty: -1, courage: 2, wisdom: -1, righteousness: 3, freedom: 2, charisma: -2 } },
      { key: "B", text: "试着说服对方", weights: { loyalty: 0, courage: 0, wisdom: 1, righteousness: 0, freedom: -1, charisma: 4 } },
      { key: "C", text: "求同存异，不让关系僵住", weights: { loyalty: 2, courage: -1, wisdom: 1, righteousness: 0, freedom: -2, charisma: 3 } },
      { key: "D", text: "无所谓，各干各的", weights: { loyalty: -2, courage: 0, wisdom: 0, righteousness: -1, freedom: 4, charisma: -2 } },
    ],
  },
  { id: "q17", text: "你认为什么样的承诺可以打破？",
    options: [
      { key: "A", text: "什么承诺都不能打破", weights: { loyalty: 3, courage: 0, wisdom: -2, righteousness: 4, freedom: -3, charisma: 0 } },
      { key: "B", text: "对方先失信在先", weights: { loyalty: -2, courage: 1, wisdom: 2, righteousness: 0, freedom: 2, charisma: 0 } },
      { key: "C", text: "形势所迫，没法遵守", weights: { loyalty: -1, courage: 0, wisdom: 3, righteousness: -2, freedom: 2, charisma: 0 } },
      { key: "D", text: "看情况，承诺只是当时的话", weights: { loyalty: -3, courage: 0, wisdom: 1, righteousness: -3, freedom: 4, charisma: 0 } },
    ],
  },
  { id: "q18", text: "有人劝你做一件违背原则但有利可图的事，你会？",
    options: [
      { key: "A", text: "坚决不干，原则不能破", weights: { loyalty: 0, courage: 1, wisdom: -2, righteousness: 4, freedom: -1, charisma: 0 } },
      { key: "B", text: "看看利益有多大，再决定", weights: { loyalty: -1, courage: 0, wisdom: 2, righteousness: -3, freedom: 1, charisma: 1 } },
      { key: "C", text: "不干，但不想得罪这个人", weights: { loyalty: 1, courage: -2, wisdom: 1, righteousness: 2, freedom: -1, charisma: 2 } },
      { key: "D", text: "干了再说，反正没人知道", weights: { loyalty: -2, courage: 1, wisdom: 0, righteousness: -4, freedom: 2, charisma: -1 } },
    ],
  },
  { id: "q19", text: "如果你陷入绝境，你会？",
    options: [
      { key: "A", text: "拼了，杀出一条血路", weights: { loyalty: 0, courage: 4, wisdom: -3, righteousness: 0, freedom: 2, charisma: 0 } },
      { key: "B", text: "等待时机，不急于行动", weights: { loyalty: 0, courage: -2, wisdom: 4, righteousness: 0, freedom: 1, charisma: 0 } },
      { key: "C", text: "找人帮忙，看看有没有出路", weights: { loyalty: 1, courage: -1, wisdom: 1, righteousness: 0, freedom: -2, charisma: 3 } },
      { key: "D", text: "先保命，其他以后再说", weights: { loyalty: -1, courage: -2, wisdom: 3, righteousness: -1, freedom: 1, charisma: 0 } },
    ],
  },
  { id: "q20", text: "面对一个比你强很多的对手，你会？",
    options: [
      { key: "A", text: "硬碰硬，不惧怕任何人", weights: { loyalty: 0, courage: 4, wisdom: -3, righteousness: 2, freedom: 1, charisma: 0 } },
      { key: "B", text: "避其锋芒，找机会反制", weights: { loyalty: 0, courage: -2, wisdom: 4, righteousness: 0, freedom: 2, charisma: 0 } },
      { key: "C", text: "拉拢别人，一起对付", weights: { loyalty: 1, courage: -1, wisdom: 1, righteousness: 0, freedom: -2, charisma: 4 } },
      { key: "D", text: "先退一步，保存实力", weights: { loyalty: 0, courage: -2, wisdom: 3, righteousness: -1, freedom: 1, charisma: 0 } },
    ],
  },
  { id: "q21", text: "事情搞砸了，你觉得最可能是什么原因？",
    options: [
      { key: "A", text: "自己判断失误", weights: { loyalty: 0, courage: 0, wisdom: 3, righteousness: 0, freedom: -1, charisma: -1 } },
      { key: "B", text: "出力的人不给力", weights: { loyalty: -2, courage: 0, wisdom: 0, righteousness: 0, freedom: 0, charisma: 3 } },
      { key: "C", text: "运气不好", weights: { loyalty: 0, courage: 0, wisdom: -2, righteousness: -1, freedom: 3, charisma: 0 } },
      { key: "D", text: "动手太晚了", weights: { loyalty: 0, courage: 3, wisdom: 1, righteousness: 0, freedom: 0, charisma: -1 } },
    ],
  },
  { id: "q22", text: "你觉得什么是真正的勇敢？",
    options: [
      { key: "A", text: "明知危险还敢冲上去", weights: { loyalty: 0, courage: 4, wisdom: -2, righteousness: 1, freedom: 1, charisma: 0 } },
      { key: "B", text: "敢于承认错误", weights: { loyalty: 1, courage: 0, wisdom: 1, righteousness: 3, freedom: 0, charisma: 1 } },
      { key: "C", text: "在压力下不低头", weights: { loyalty: 1, courage: 3, wisdom: -1, righteousness: 3, freedom: 0, charisma: 0 } },
      { key: "D", text: "敢于打破常规", weights: { loyalty: -1, courage: 2, wisdom: 0, righteousness: -1, freedom: 4, charisma: 0 } },
    ],
  },
  { id: "q23", text: "如果你不得不背黑锅，你会？",
    options: [
      { key: "A", text: "宁愿死也不认", weights: { loyalty: 0, courage: 3, wisdom: -3, righteousness: 3, freedom: 1, charisma: -1 } },
      { key: "B", text: "看为谁背，值得就认", weights: { loyalty: 4, courage: 0, wisdom: 1, righteousness: -1, freedom: -2, charisma: 0 } },
      { key: "C", text: "先认了，日后再说清楚", weights: { loyalty: 0, courage: -1, wisdom: 3, righteousness: -1, freedom: 1, charisma: 1 } },
      { key: "D", text: "绝对不干，凭什么我背", weights: { loyalty: -2, courage: 2, wisdom: 0, righteousness: 0, freedom: 4, charisma: -1 } },
    ],
  },
  { id: "q24", text: "你觉得什么时候可以背叛？",
    options: [
      { key: "A", text: "什么时候都不可以", weights: { loyalty: 4, courage: 0, wisdom: -2, righteousness: 3, freedom: -3, charisma: 0 } },
      { key: "B", text: "对方先背叛在先", weights: { loyalty: -2, courage: 1, wisdom: 2, righteousness: 1, freedom: 1, charisma: 0 } },
      { key: "C", text: "身不由己的时候", weights: { loyalty: -2, courage: 0, wisdom: 1, righteousness: -1, freedom: 2, charisma: 0 } },
      { key: "D", text: "为了更大的目标", weights: { loyalty: -3, courage: 0, wisdom: 2, righteousness: -2, freedom: 2, charisma: 1 } },
    ],
  },
  { id: "q25", text: "如果只能选一个，你最看重什么？",
    options: [
      { key: "A", text: "名声", weights: { loyalty: 0, courage: 0, wisdom: 0, righteousness: 2, freedom: -2, charisma: 4 } },
      { key: "B", text: "自由", weights: { loyalty: -2, courage: 1, wisdom: 0, righteousness: -1, freedom: 4, charisma: -1 } },
      { key: "C", text: "兄弟", weights: { loyalty: 4, courage: 0, wisdom: -1, righteousness: 1, freedom: -2, charisma: 2 } },
      { key: "D", text: "胜负", weights: { loyalty: 0, courage: 3, wisdom: 2, righteousness: 0, freedom: 1, charisma: 0 } },
    ],
  },
  { id: "q26", text: "你认为什么是真正的义气？",
    options: [
      { key: "A", text: "有福同享有难同当", weights: { loyalty: 3, courage: 0, wisdom: -1, righteousness: 0, freedom: -2, charisma: 3 } },
      { key: "B", text: "关键时刻站出来", weights: { loyalty: 2, courage: 3, wisdom: 0, righteousness: 2, freedom: 0, charisma: -1 } },
      { key: "C", text: "不说朋友坏话", weights: { loyalty: 3, courage: -1, wisdom: 1, righteousness: 2, freedom: -1, charisma: 0 } },
      { key: "D", text: "帮朋友解决麻烦", weights: { loyalty: 2, courage: 2, wisdom: 1, righteousness: 0, freedom: 0, charisma: 1 } },
    ],
  },
  { id: "q27", text: "你愿意为谁牺牲？",
    options: [
      { key: "A", text: "值得信任的人", weights: { loyalty: 3, courage: 0, wisdom: 1, righteousness: 0, freedom: -2, charisma: 1 } },
      { key: "B", text: "只有对方也愿意为我牺牲", weights: { loyalty: 1, courage: -1, wisdom: 2, righteousness: 2, freedom: 0, charisma: 0 } },
      { key: "C", text: "任何人都不值得牺牲", weights: { loyalty: -3, courage: -1, wisdom: 0, righteousness: -1, freedom: 4, charisma: -1 } },
      { key: "D", text: "自己的理想和信念", weights: { loyalty: -1, courage: 2, wisdom: 0, righteousness: 4, freedom: 1, charisma: 0 } },
    ],
  },
  { id: "q28", text: "如果有人用你的弱点要挟你，你会？",
    options: [
      { key: "A", text: "宁死不从", weights: { loyalty: 0, courage: 4, wisdom: -2, righteousness: 3, freedom: 1, charisma: -1 } },
      { key: "B", text: "表面答应，暗地找机会反击", weights: { loyalty: 0, courage: 1, wisdom: 4, righteousness: -1, freedom: 1, charisma: 0 } },
      { key: "C", text: "先答应，再想办法", weights: { loyalty: 0, courage: -1, wisdom: 3, righteousness: -1, freedom: 1, charisma: 1 } },
      { key: "D", text: "直接摊牌，看谁怕谁", weights: { loyalty: -1, courage: 4, wisdom: -2, righteousness: 0, freedom: 3, charisma: 0 } },
    ],
  },
  { id: "q29", text: "你认为成功靠什么？",
    options: [
      { key: "A", text: "自己的本事", weights: { loyalty: -1, courage: 1, wisdom: 3, righteousness: 0, freedom: 1, charisma: -1 } },
      { key: "B", text: "机遇和运气", weights: { loyalty: 0, courage: 0, wisdom: 0, righteousness: -1, freedom: 3, charisma: 0 } },
      { key: "C", text: "贵人相助", weights: { loyalty: 1, courage: -1, wisdom: 0, righteousness: 0, freedom: -2, charisma: 4 } },
      { key: "D", text: "该出手时就出手", weights: { loyalty: 0, courage: 4, wisdom: -1, righteousness: 0, freedom: 2, charisma: 0 } },
    ],
  },
  { id: "q30", text: "你更在意别人怎么看你吗？",
    options: [
      { key: "A", text: "很在意，名声很重要", weights: { loyalty: 0, courage: 0, wisdom: 0, righteousness: 2, freedom: -3, charisma: 4 } },
      { key: "B", text: "在意，但不会为此改变自己", weights: { loyalty: 0, courage: 0, wisdom: 1, righteousness: 2, freedom: 1, charisma: 0 } },
      { key: "C", text: "不太在意，过好自己的日子", weights: { loyalty: 0, courage: 0, wisdom: 0, righteousness: -1, freedom: 3, charisma: -1 } },
      { key: "D", text: "完全不在意，随他们怎么想", weights: { loyalty: -1, courage: 0, wisdom: 0, righteousness: -1, freedom: 4, charisma: -3 } },
    ],
  },
  { id: "q31", text: "如果你有本事，你会选择怎么用？",
    options: [
      { key: "A", text: "找值得追随的人，跟着干", weights: { loyalty: 4, courage: -1, wisdom: 0, righteousness: 0, freedom: -3, charisma: 2 } },
      { key: "B", text: "自己干，闯出一片天", weights: { loyalty: -2, courage: 3, wisdom: 0, righteousness: 0, freedom: 4, charisma: 0 } },
      { key: "C", text: "低调行事，不显山露水", weights: { loyalty: 0, courage: -2, wisdom: 4, righteousness: 0, freedom: 2, charisma: -2 } },
      { key: "D", text: "用来保护自己在乎的人", weights: { loyalty: 3, courage: 1, wisdom: 0, righteousness: 3, freedom: -1, charisma: 0 } },
    ],
  },
  { id: "q32", text: "你觉得什么样的人不能深交？",
    options: [
      { key: "A", text: "见风使舵的人", weights: { loyalty: 3, courage: 0, wisdom: 0, righteousness: 2, freedom: -1, charisma: -1 } },
      { key: "B", text: "没有底线的人", weights: { loyalty: 0, courage: 0, wisdom: 2, righteousness: 4, freedom: -1, charisma: 0 } },
      { key: "C", text: "优柔寡断的人", weights: { loyalty: 0, courage: 3, wisdom: 0, righteousness: 0, freedom: 1, charisma: -1 } },
      { key: "D", text: "管得太多的人", weights: { loyalty: -1, courage: 0, wisdom: 0, righteousness: 0, freedom: 4, charisma: -2 } },
    ],
  },
  { id: "q33", text: "面对招安（被官方收编），你会？",
    options: [
      { key: "A", text: "接受，正规军更有前途", weights: { loyalty: 2, courage: -1, wisdom: 2, righteousness: 0, freedom: -3, charisma: 1 } },
      { key: "B", text: "不接受，自由最重要", weights: { loyalty: -1, courage: 2, wisdom: 0, righteousness: 0, freedom: 4, charisma: -1 } },
      { key: "C", text: "看兄弟们怎么选", weights: { loyalty: 4, courage: 0, wisdom: -1, righteousness: 0, freedom: -2, charisma: 2 } },
      { key: "D", text: "假意接受，实则另有所图", weights: { loyalty: -2, courage: 0, wisdom: 4, righteousness: -2, freedom: 1, charisma: 0 } },
    ],
  },
  { id: "q34", text: "如果梁山排座次，你觉得自己适合什么位置？",
    options: [
      { key: "A", text: "头把交椅，说了算", weights: { loyalty: 0, courage: 1, wisdom: -1, righteousness: 0, freedom: 0, charisma: 4 } },
      { key: "B", text: "军师位置，出谋划策", weights: { loyalty: 0, courage: -2, wisdom: 4, righteousness: 0, freedom: 2, charisma: 0 } },
      { key: "C", text: "先锋位置，冲锋陷阵", weights: { loyalty: 0, courage: 4, wisdom: -2, righteousness: 1, freedom: 0, charisma: 0 } },
      { key: "D", text: "无所谓，不争这个", weights: { loyalty: 0, courage: -1, wisdom: 0, righteousness: 0, freedom: 4, charisma: -2 } },
    ],
  },
  { id: "q35", text: "你觉得兄弟之间最重要的是什么？",
    options: [
      { key: "A", text: "有难同当", weights: { loyalty: 4, courage: 1, wisdom: -1, righteousness: 1, freedom: -2, charisma: 0 } },
      { key: "B", text: "互相信任", weights: { loyalty: 3, courage: 0, wisdom: 0, righteousness: 1, freedom: -1, charisma: 2 } },
      { key: "C", text: "彼此不坑", weights: { loyalty: 2, courage: 0, wisdom: 1, righteousness: 3, freedom: 0, charisma: 0 } },
      { key: "D", text: "一起痛快", weights: { loyalty: 0, courage: 0, wisdom: -1, righteousness: -2, freedom: 3, charisma: 3 } },
    ],
  },
  { id: "q36", text: "如果有人让你做不想做的事，你会？",
    options: [
      { key: "A", text: "直接拒绝，管他是谁", weights: { loyalty: -2, courage: 3, wisdom: -1, righteousness: 0, freedom: 4, charisma: -1 } },
      { key: "B", text: "看对方是谁，再决定", weights: { loyalty: 2, courage: -1, wisdom: 2, righteousness: 0, freedom: -2, charisma: 1 } },
      { key: "C", text: "找个借口推掉", weights: { loyalty: 0, courage: -1, wisdom: 3, righteousness: 0, freedom: 1, charisma: 0 } },
      { key: "D", text: "如果是为了大局，可以勉强", weights: { loyalty: 2, courage: 0, wisdom: 0, righteousness: 2, freedom: -3, charisma: 1 } },
    ],
  },
  { id: "q37", text: "你认为什么是真正的忠义？",
    options: [
      { key: "A", text: "说到做到，绝不食言", weights: { loyalty: 2, courage: 0, wisdom: -1, righteousness: 4, freedom: -2, charisma: 1 } },
      { key: "B", text: "跟随一个人到底", weights: { loyalty: 4, courage: 0, wisdom: -2, righteousness: 1, freedom: -3, charisma: 0 } },
      { key: "C", text: "不背叛自己的信念", weights: { loyalty: 0, courage: 1, wisdom: 0, righteousness: 4, freedom: 2, charisma: -1 } },
      { key: "D", text: "关键时刻不离不弃", weights: { loyalty: 4, courage: 2, wisdom: -1, righteousness: 1, freedom: -2, charisma: 0 } },
    ],
  },
  { id: "q38", text: "如果让你选择一种方式离开梁山，你会？",
    options: [
      { key: "A", text: "功成身退，归隐山林", weights: { loyalty: -1, courage: -2, wisdom: 3, righteousness: 0, freedom: 4, charisma: -1 } },
      { key: "B", text: "战死沙场，轰轰烈烈", weights: { loyalty: 0, courage: 4, wisdom: -1, righteousness: 2, freedom: 0, charisma: 0 } },
      { key: "C", text: "跟着兄弟们走到底", weights: { loyalty: 4, courage: 0, wisdom: -1, righteousness: 1, freedom: -3, charisma: 2 } },
      { key: "D", text: "找机会自立门户", weights: { loyalty: -3, courage: 2, wisdom: 1, righteousness: -1, freedom: 4, charisma: 1 } },
    ],
  },
  { id: "q39", text: "你觉得什么人最可怕？",
    options: [
      { key: "A", text: "没有底线的人", weights: { loyalty: 0, courage: 0, wisdom: 1, righteousness: 4, freedom: 0, charisma: -1 } },
      { key: "B", text: "城府太深的人", weights: { loyalty: 0, courage: -1, wisdom: 2, righteousness: 0, freedom: 1, charisma: 0 } },
      { key: "C", text: "当面一套背后一套的人", weights: { loyalty: 2, courage: 0, wisdom: 0, righteousness: 3, freedom: -1, charisma: 0 } },
      { key: "D", text: "死缠烂打的人", weights: { loyalty: 0, courage: 0, wisdom: -1, righteousness: 0, freedom: 3, charisma: -2 } },
    ],
  },
  { id: "q40", text: "如果让你用一句话形容自己，你会说？",
    options: [
      { key: "A", text: "我是重情义的人", weights: { loyalty: 4, courage: 0, wisdom: 0, righteousness: 0, freedom: -2, charisma: 2 } },
      { key: "B", text: "我是有原则的人", weights: { loyalty: 0, courage: 0, wisdom: 0, righteousness: 4, freedom: -1, charisma: 0 } },
      { key: "C", text: "我是敢作敢为的人", weights: { loyalty: 0, courage: 4, wisdom: -1, righteousness: 0, freedom: 1, charisma: 0 } },
      { key: "D", text: "我是活得自在的人", weights: { loyalty: -2, courage: 0, wisdom: 0, righteousness: -1, freedom: 4, charisma: 0 } },
    ],
  },
];

if (typeof window !== "undefined") { window.SHUIHU_DATA = { DIMENSIONS, CHARACTERS, QUESTIONS }; }
if (typeof module !== "undefined") { module.exports = { DIMENSIONS, CHARACTERS, QUESTIONS }; }
