const DIMENSIONS = [
  "loyalty",
  "courage",
  "wisdom",
  "righteousness",
  "freedom",
  "charisma",
];

const CHARACTERS = [
  {
    id: "song_jiang",
    name: "宋江",
    nickname: "及时雨",
    archetype: "忠义凝聚型领导",
    tags: ["忠义", "凝聚", "宽厚", "抱负"],
    scores: { loyalty: 95, courage: 35, wisdom: 55, righteousness: 70, freedom: 20, charisma: 92 },
  },
  {
    id: "lu_junyi",
    name: "卢俊义",
    nickname: "玉麒麟",
    archetype: "英武忠厚型统帅",
    tags: ["英武", "忠厚", "名声", "正道"],
    scores: { loyalty: 70, courage: 72, wisdom: 40, righteousness: 68, freedom: 25, charisma: 60 },
  },
  {
    id: "wu_yong",
    name: "吴用",
    nickname: "智多星",
    archetype: "智谋型军师",
    tags: ["智谋", "筹策", "权变", "辅佐"],
    scores: { loyalty: 55, courage: 25, wisdom: 95, righteousness: 35, freedom: 30, charisma: 45 },
  },
  {
    id: "gongsun_sheng",
    name: "公孙胜",
    nickname: "入云龙",
    archetype: "超脱淡泊型隐士",
    tags: ["超脱", "淡泊", "灵慧", "自由"],
    scores: { loyalty: 35, courage: 45, wisdom: 88, righteousness: 50, freedom: 95, charisma: 30 },
  },
  {
    id: "guan_sheng",
    name: "关胜",
    nickname: "大刀",
    archetype: "威严正统型猛将",
    tags: ["威严", "正统", "忠烈", "名节"],
    scores: { loyalty: 85, courage: 75, wisdom: 35, righteousness: 85, freedom: 15, charisma: 50 },
  },
  {
    id: "lin_chong",
    name: "林冲",
    nickname: "豹子头",
    archetype: "隐忍刚烈型武将",
    tags: ["隐忍", "刚烈", "被迫", "正道"],
    scores: { loyalty: 60, courage: 70, wisdom: 40, righteousness: 78, freedom: 18, charisma: 35 },
  },
  {
    id: "qin_ming",
    name: "秦明",
    nickname: "霹雳火",
    archetype: "刚烈暴躁型先锋",
    tags: ["暴烈", "果决", "先锋", "刚烈"],
    scores: { loyalty: 68, courage: 92, wisdom: 15, righteousness: 50, freedom: 40, charisma: 38 },
  },
  {
    id: "hua_rong",
    name: "花荣",
    nickname: "小李广",
    archetype: "忠诚优雅型将领",
    tags: ["忠诚", "优雅", "精准", "重情"],
    scores: { loyalty: 95, courage: 62, wisdom: 48, righteousness: 72, freedom: 28, charisma: 52 },
  },
  {
    id: "chai_jin",
    name: "柴进",
    nickname: "小旋风",
    archetype: "仗义疏财型贵族",
    tags: ["仗义", "疏财", "贵族", "礼贤"],
    scores: { loyalty: 55, courage: 30, wisdom: 48, righteousness: 62, freedom: 55, charisma: 72 },
  },
  {
    id: "lu_zhishen",
    name: "鲁智深",
    nickname: "花和尚",
    archetype: "豪爽正义型好汉",
    tags: ["豪爽", "正义", "粗中有细", "慈悲"],
    scores: { loyalty: 75, courage: 88, wisdom: 42, righteousness: 92, freedom: 78, charisma: 68 },
  },
  {
    id: "wu_song",
    name: "武松",
    nickname: "行者",
    archetype: "刚烈果敢型英雄",
    tags: ["刚烈", "果敢", "嫉恶", "复仇"],
    scores: { loyalty: 65, courage: 95, wisdom: 35, righteousness: 82, freedom: 60, charisma: 50 },
  },
  {
    id: "dong_ping",
    name: "董平",
    nickname: "双枪将",
    archetype: "野心果决型将领",
    tags: ["果决", "野心", "双面", "灵活"],
    scores: { loyalty: 30, courage: 82, wisdom: 52, righteousness: 25, freedom: 58, charisma: 62 },
  },
  {
    id: "yang_zhi",
    name: "杨志",
    nickname: "青面兽",
    archetype: "志高运蹇型英雄",
    tags: ["志高", "运蹇", "刚直", "不甘"],
    scores: { loyalty: 50, courage: 70, wisdom: 35, righteousness: 58, freedom: 22, charisma: 30 },
  },
  {
    id: "dai_zong",
    name: "戴宗",
    nickname: "神行太保",
    archetype: "机敏务实型执行者",
    tags: ["机敏", "务实", "执行", "快速"],
    scores: { loyalty: 62, courage: 48, wisdom: 55, righteousness: 48, freedom: 42, charisma: 40 },
  },
  {
    id: "li_kui",
    name: "李逵",
    nickname: "黑旋风",
    archetype: "粗犷直率型猛将",
    tags: ["粗犷", "直率", "忠义", "冲动"],
    scores: { loyalty: 88, courage: 98, wisdom: 8, righteousness: 45, freedom: 70, charisma: 42 },
  },
  {
    id: "shi_jin",
    name: "史进",
    nickname: "九纹龙",
    archetype: "热血少年型好汉",
    tags: ["热血", "少年", "好武", "单纯"],
    scores: { loyalty: 68, courage: 80, wisdom: 20, righteousness: 55, freedom: 65, charisma: 38 },
  },
  {
    id: "shi_xiu",
    name: "石秀",
    nickname: "拼命三郎",
    archetype: "精明果敢型行动者",
    tags: ["精明", "果敢", "拼命", "敏锐"],
    scores: { loyalty: 65, courage: 85, wisdom: 62, righteousness: 52, freedom: 48, charisma: 32 },
  },
  {
    id: "yan_qing",
    name: "燕青",
    nickname: "浪子",
    archetype: "聪慧灵动型浪子",
    tags: ["聪慧", "灵动", "多才", "忠心"],
    scores: { loyalty: 78, courage: 52, wisdom: 78, righteousness: 52, freedom: 72, charisma: 75 },
  },
  {
    id: "zhang_shun",
    name: "张顺",
    nickname: "浪里白条",
    archetype: "水上豪杰型义士",
    tags: ["勇猛", "义气", "水战", "信义"],
    scores: { loyalty: 78, courage: 82, wisdom: 30, righteousness: 65, freedom: 48, charisma: 42 },
  },
  {
    id: "ruan_xiaoqi",
    name: "阮小七",
    nickname: "活阎罗",
    archetype: "豪放不羁型渔民",
    tags: ["豪放", "不羁", "江湖", "自在"],
    scores: { loyalty: 55, courage: 82, wisdom: 22, righteousness: 40, freedom: 92, charisma: 35 },
  },
  {
    id: "zhu_tong",
    name: "朱仝",
    nickname: "美髯公",
    archetype: "仁义温和型义士",
    tags: ["仁义", "温和", "重情", "体面"],
    scores: { loyalty: 85, courage: 58, wisdom: 42, righteousness: 78, freedom: 32, charisma: 52 },
  },
  {
    id: "li_jun",
    name: "李俊",
    nickname: "混江龙",
    archetype: "自主独立型水上首领",
    tags: ["自主", "独立", "远见", "开拓"],
    scores: { loyalty: 45, courage: 72, wisdom: 62, righteousness: 42, freedom: 82, charisma: 58 },
  },
  {
    id: "lei_heng",
    name: "雷横",
    nickname: "插翅虎",
    archetype: "正直勇猛型都头",
    tags: ["正直", "勇猛", "讲理", "忠义"],
    scores: { loyalty: 78, courage: 70, wisdom: 32, righteousness: 72, freedom: 28, charisma: 38 },
  },
  {
    id: "shi_qian",
    name: "时迁",
    nickname: "鼓上蚤",
    archetype: "灵活机巧型奇才",
    tags: ["灵活", "机巧", "非常规", "实用"],
    scores: { loyalty: 45, courage: 42, wisdom: 58, righteousness: 28, freedom: 78, charisma: 28 },
  },
];

const QUESTIONS = [
  {
    id: "q01",
    text: "团队遇到一个高风险但高回报的机会，你通常怎么做？",
    options: [
      { key: "A", text: "先评估风险，确认可控再行动", weights: { courage: -2, wisdom: 2 } },
      { key: "B", text: "机不可失，先抢占位置再说", weights: { courage: 3, freedom: 1 } },
      { key: "C", text: "召集伙伴一起商量决定", weights: { loyalty: 2, charisma: 2 } },
      { key: "D", text: "分析背后利益，判断值不值得", weights: { wisdom: 2, righteousness: -1 } },
    ],
  },
  {
    id: "q02",
    text: "当你发现原计划很难成功时，你会？",
    options: [
      { key: "A", text: "咬牙坚持，不能轻易放弃", weights: { righteousness: 2, courage: 1 } },
      { key: "B", text: "立刻调整方案，结果比面子重要", weights: { wisdom: 1, freedom: 2 } },
      { key: "C", text: "稳住大家情绪，再想办法", weights: { loyalty: 2, charisma: 1 } },
      { key: "D", text: "暂时蛰伏，等待更好时机", weights: { wisdom: 2, courage: -2 } },
    ],
  },
  {
    id: "q03",
    text: "面对不熟悉的新领域，你更可能？",
    options: [
      { key: "A", text: "直接上手，在实践中摸索", weights: { courage: 3, freedom: 1 } },
      { key: "B", text: "找有经验的人请教", weights: { wisdom: 2, loyalty: 1 } },
      { key: "C", text: "判断它能否带来实际收益", weights: { wisdom: 1, righteousness: -1 } },
      { key: "D", text: "先观察别人怎么做", weights: { wisdom: 1, courage: -2 } },
    ],
  },
  {
    id: "q04",
    text: "如果你有一次孤注一掷的机会，你会？",
    options: [
      { key: "A", text: "看准了就敢赌", weights: { courage: 4, freedom: 1 } },
      { key: "B", text: "会考虑这会不会牵连身边人", weights: { loyalty: 3, righteousness: 1 } },
      { key: "C", text: "先想好退路，再做决定", weights: { wisdom: 2, courage: -1 } },
      { key: "D", text: "除非别无选择，否则不会押上全部", weights: { wisdom: 2, courage: -3 } },
    ],
  },
  {
    id: "q05",
    text: "你更欣赏哪种做事方式？",
    options: [
      { key: "A", text: "稳扎稳打，靠长期积累取胜", weights: { loyalty: 2, wisdom: 1 } },
      { key: "B", text: "出奇制胜，一战改变局面", weights: { courage: 3, wisdom: 1 } },
      { key: "C", text: "众人同心，一起把事做成", weights: { charisma: 3, loyalty: 1 } },
      { key: "D", text: "精准算计，用最小代价赢", weights: { wisdom: 3, righteousness: -1 } },
    ],
  },
  {
    id: "q06",
    text: "做重要决定时，你最看重什么？",
    options: [
      { key: "A", text: "是否符合自己的原则", weights: { righteousness: 4, loyalty: 1 } },
      { key: "B", text: "能否实现目标", weights: { courage: 1, wisdom: 1 } },
      { key: "C", text: "是否留有余地", weights: { wisdom: 1, freedom: 1 } },
      { key: "D", text: "是否对关系有利", weights: { loyalty: 2, charisma: 2 } },
    ],
  },
  {
    id: "q07",
    text: "如果一件事手段不漂亮但结果很好，你怎么看？",
    options: [
      { key: "A", text: "底线不能破，否则赢了也不稳", weights: { righteousness: 4, loyalty: 1 } },
      { key: "B", text: "结果最重要，过程可以妥协", weights: { wisdom: 1, freedom: 2, righteousness: -2 } },
      { key: "C", text: "只要不伤无辜，可以接受", weights: { loyalty: 1, righteousness: 1 } },
      { key: "D", text: "看具体代价，不能一概而论", weights: { wisdom: 2 } },
    ],
  },
  {
    id: "q08",
    text: "你如何看待规则？",
    options: [
      { key: "A", text: "规则是秩序的基础，应该遵守", weights: { righteousness: 3, loyalty: 1 } },
      { key: "B", text: "规则可以变通，关键是目的", weights: { freedom: 3, wisdom: 1 } },
      { key: "C", text: "不公平的规则就该打破", weights: { courage: 2, righteousness: 2 } },
      { key: "D", text: "规则是工具，看你怎么用", weights: { wisdom: 2, freedom: 1 } },
    ],
  },
  {
    id: "q09",
    text: "当形势突然恶化时，你的第一反应是？",
    options: [
      { key: "A", text: "冷静分析，找到关键变量", weights: { wisdom: 4, courage: -1 } },
      { key: "B", text: "先稳住阵脚，保护身边的人", weights: { loyalty: 3, charisma: 1 } },
      { key: "C", text: "迎难而上，用行动打破僵局", weights: { courage: 4, freedom: 1 } },
      { key: "D", text: "寻找退路，先保证安全", weights: { wisdom: 1, freedom: 1, courage: -2 } },
    ],
  },
  {
    id: "q10",
    text: "如果你被逼到绝境，你会？",
    options: [
      { key: "A", text: "拼了，反正没有退路", weights: { courage: 4, righteousness: 1 } },
      { key: "B", text: "寻找对方破绽，以退为进", weights: { wisdom: 3, freedom: 1 } },
      { key: "C", text: "向信任的人求助", weights: { loyalty: 3, charisma: 1 } },
      { key: "D", text: "暂时隐忍，等待翻盘时机", weights: { wisdom: 2, courage: -1 } },
    ],
  },
  {
    id: "q11",
    text: "团队士气低落时，你会？",
    options: [
      { key: "A", text: "站出来鼓舞大家", weights: { charisma: 3, courage: 2 } },
      { key: "B", text: "先找一个小胜利恢复信心", weights: { wisdom: 3, charisma: 1 } },
      { key: "C", text: "安抚大家，重建信任", weights: { loyalty: 3, charisma: 1 } },
      { key: "D", text: "分析问题，给出可行方案", weights: { wisdom: 3, righteousness: 1 } },
    ],
  },
  {
    id: "q12",
    text: "面对比你强大得多的对手，你会？",
    options: [
      { key: "A", text: "正面硬刚，不惧强权", weights: { courage: 4, righteousness: 1 } },
      { key: "B", text: "用智慧周旋，寻找破绽", weights: { wisdom: 4, freedom: 1 } },
      { key: "C", text: "联合其他人一起对抗", weights: { charisma: 3, loyalty: 1 } },
      { key: "D", text: "先退一步，保存实力", weights: { wisdom: 2, freedom: 1 } },
    ],
  },
  {
    id: "q13",
    text: "你最怕在危机中遇到什么？",
    options: [
      { key: "A", text: "身边人背叛", weights: { loyalty: 4, righteousness: 1 } },
      { key: "B", text: "信息不足，无法判断", weights: { wisdom: 3 } },
      { key: "C", text: "无法行动，被困住", weights: { freedom: 3, courage: 1 } },
      { key: "D", text: "失去控制权", weights: { charisma: 2, courage: 1 } },
    ],
  },
  {
    id: "q14",
    text: "朋友遇到麻烦但帮他会影响你的利益，你会？",
    options: [
      { key: "A", text: "能帮就帮，情义不能只看得失", weights: { loyalty: 4, righteousness: 1 } },
      { key: "B", text: "先判断会不会把自己拖下水", weights: { wisdom: 2, freedom: 1 } },
      { key: "C", text: "帮，但要设定边界", weights: { loyalty: 1, wisdom: 1 } },
      { key: "D", text: "看这段关系值不值得投入", weights: { wisdom: 2, loyalty: -1 } },
    ],
  },
  {
    id: "q15",
    text: "在一个新团队里，你会优先建立什么？",
    options: [
      { key: "A", text: "信任关系", weights: { loyalty: 3, charisma: 2 } },
      { key: "B", text: "权责边界", weights: { righteousness: 2, wisdom: 1 } },
      { key: "C", text: "个人影响力", weights: { charisma: 3, courage: 1 } },
      { key: "D", text: "信息渠道", weights: { wisdom: 3, freedom: 1 } },
    ],
  },
  {
    id: "q16",
    text: "你和朋友意见冲突时，你通常？",
    options: [
      { key: "A", text: "直接说清楚，不憋着", weights: { courage: 2, righteousness: 1 } },
      { key: "B", text: "先照顾对方感受", weights: { loyalty: 3, charisma: 1 } },
      { key: "C", text: "用事实和逻辑说服对方", weights: { wisdom: 3, righteousness: 1 } },
      { key: "D", text: "暂时不争，等时机成熟", weights: { wisdom: 2, freedom: 1 } },
    ],
  },
  {
    id: "q17",
    text: "你最看重朋友的什么品质？",
    options: [
      { key: "A", text: "信义，说到做到", weights: { loyalty: 4, righteousness: 1 } },
      { key: "B", text: "真诚，没有心机", weights: { loyalty: 2, charisma: 1 } },
      { key: "C", text: "聪明，有见地", weights: { wisdom: 3 } },
      { key: "D", text: "有趣，自在不拘", weights: { freedom: 3, charisma: 1 } },
    ],
  },
  {
    id: "q18",
    text: "你最希望别人如何评价你？",
    options: [
      { key: "A", text: "可靠", weights: { loyalty: 3, righteousness: 1 } },
      { key: "B", text: "强大", weights: { courage: 2, charisma: 1 } },
      { key: "C", text: "有情义", weights: { loyalty: 3, charisma: 1 } },
      { key: "D", text: "自由", weights: { freedom: 4, courage: 1 } },
    ],
  },
  {
    id: "q19",
    text: "你认为最重要的是？",
    options: [
      { key: "A", text: "情义", weights: { loyalty: 4, charisma: 1 } },
      { key: "B", text: "自由", weights: { freedom: 4, courage: 1 } },
      { key: "C", text: "成就", weights: { courage: 2, wisdom: 1 } },
      { key: "D", text: "正道", weights: { righteousness: 4, wisdom: 1 } },
    ],
  },
  {
    id: "q20",
    text: "如果必须选一个人生关键词，你会选？",
    options: [
      { key: "A", text: "忠义", weights: { loyalty: 4, righteousness: 1 } },
      { key: "B", text: "权变", weights: { freedom: 3, wisdom: 1 } },
      { key: "C", text: "突破", weights: { courage: 3, freedom: 1 } },
      { key: "D", text: "智谋", weights: { wisdom: 4, freedom: 1 } },
    ],
  },
  {
    id: "q21",
    text: "你更不能接受别人哪种行为？",
    options: [
      { key: "A", text: "背信弃义", weights: { loyalty: 4, righteousness: 2 } },
      { key: "B", text: "愚蠢低效", weights: { wisdom: 2, courage: 1 } },
      { key: "C", text: "没有担当", weights: { courage: 3, righteousness: 1 } },
      { key: "D", text: "虚伪做作", weights: { righteousness: 2, freedom: 2 } },
    ],
  },
  {
    id: "q22",
    text: "当理想和现实冲突时，你会？",
    options: [
      { key: "A", text: "尽量守住核心理想", weights: { righteousness: 3, loyalty: 1 } },
      { key: "B", text: "调整方式，让理想能落地", weights: { wisdom: 2, freedom: 2 } },
      { key: "C", text: "先向现实低头，以后再说", weights: { freedom: 1, wisdom: 1 } },
      { key: "D", text: "换一条路，不想被困住", weights: { freedom: 3, courage: 1 } },
    ],
  },
  {
    id: "q23",
    text: "你觉得强者的责任是什么？",
    options: [
      { key: "A", text: "保护弱者", weights: { loyalty: 3, righteousness: 2 } },
      { key: "B", text: "成就自己", weights: { freedom: 3, courage: 1 } },
      { key: "C", text: "改变不公", weights: { righteousness: 3, courage: 1 } },
      { key: "D", text: "维护秩序", weights: { wisdom: 2, charisma: 1 } },
    ],
  },
  {
    id: "q24",
    text: "你如何看待隐忍？",
    options: [
      { key: "A", text: "有时是成熟的表现", weights: { wisdom: 3 } },
      { key: "B", text: "只要目标值得，就能忍", weights: { loyalty: 2, wisdom: 1 } },
      { key: "C", text: "太憋屈，不如直接解决", weights: { courage: 3, freedom: 1 } },
      { key: "D", text: "要看对象，有些人不值得忍", weights: { righteousness: 2, wisdom: 1 } },
    ],
  },
  {
    id: "q25",
    text: "如果你身处乱世，最想守住什么？",
    options: [
      { key: "A", text: "身边人的安全", weights: { loyalty: 4, charisma: 1 } },
      { key: "B", text: "自己的理想和名节", weights: { righteousness: 3, loyalty: 1 } },
      { key: "C", text: "活下去并等待机会", weights: { wisdom: 2, freedom: 1 } },
      { key: "D", text: "自由，不想被任何人控制", weights: { freedom: 4, courage: 1 } },
    ],
  },
  {
    id: "q26",
    text: "你更愿意接受哪种结局？",
    options: [
      { key: "A", text: "没有站到最高处，但问心无愧", weights: { righteousness: 3, loyalty: 1 } },
      { key: "B", text: "隐忍多年，最后掌握局面", weights: { wisdom: 2, freedom: 1 } },
      { key: "C", text: "经历很多争议，但完成大事", weights: { courage: 2, wisdom: 1 } },
      { key: "D", text: "灿烂一时，即使代价很高", weights: { courage: 3, freedom: 2 } },
    ],
  },
  {
    id: "q27",
    text: "你更适合在团队里扮演？",
    options: [
      { key: "A", text: "头领，负责方向和凝聚", weights: { charisma: 4, loyalty: 1 } },
      { key: "B", text: "军师，负责判断和布局", weights: { wisdom: 4, freedom: 1 } },
      { key: "C", text: "猛将，负责突破和执行", weights: { courage: 4, freedom: 1 } },
      { key: "D", text: "联络人，负责协调和谈判", weights: { charisma: 2, freedom: 2 } },
    ],
  },
  {
    id: "q28",
    text: "你生气时通常？",
    options: [
      { key: "A", text: "直接表现出来", weights: { courage: 2, freedom: 2 } },
      { key: "B", text: "尽量控制，之后再处理", weights: { wisdom: 3, loyalty: 1 } },
      { key: "C", text: "冷处理，让对方自己意识到", weights: { freedom: 2, wisdom: 1 } },
      { key: "D", text: "转化成行动，先解决问题", weights: { courage: 2, wisdom: 1 } },
    ],
  },
  {
    id: "q29",
    text: "当你获得很大成功时，你会？",
    options: [
      { key: "A", text: "克制一点，避免招人嫉妒", weights: { wisdom: 3, loyalty: 1 } },
      { key: "B", text: "大方庆祝，成功就该被看见", weights: { courage: 2, charisma: 2 } },
      { key: "C", text: "感谢伙伴和支持者", weights: { loyalty: 3, charisma: 1 } },
      { key: "D", text: "立刻思考下一步", weights: { wisdom: 2, freedom: 1 } },
    ],
  },
  {
    id: "q30",
    text: "你更像哪种表达方式？",
    options: [
      { key: "A", text: "情绪鲜明，喜欢有话直说", weights: { courage: 2, freedom: 2 } },
      { key: "B", text: "话不多，但每句都经过考虑", weights: { wisdom: 3, righteousness: 1 } },
      { key: "C", text: "温和沟通，尽量让人舒服", weights: { loyalty: 3, charisma: 1 } },
      { key: "D", text: "说话有策略，看对象调整", weights: { wisdom: 2, freedom: 2 } },
    ],
  },
  {
    id: "q31",
    text: "当你发现自己不如别人时，你会？",
    options: [
      { key: "A", text: "默默学习，追上去", weights: { wisdom: 2, loyalty: 1 } },
      { key: "B", text: "不服气，想正面赢回来", weights: { courage: 3, freedom: 1 } },
      { key: "C", text: "接受差距，但争取合作", weights: { loyalty: 2, charisma: 1 } },
      { key: "D", text: "找自己的优势赛道", weights: { freedom: 3, wisdom: 1 } },
    ],
  },
  {
    id: "q32",
    text: "你面对长期目标时？",
    options: [
      { key: "A", text: "可以持续投入，慢慢推进", weights: { loyalty: 3, wisdom: 1 } },
      { key: "B", text: "需要阶段性成果维持动力", weights: { courage: 1, charisma: 1 } },
      { key: "C", text: "如果看不到回报会及时止损", weights: { wisdom: 2, freedom: 1 } },
      { key: "D", text: "会不断调整路线", weights: { freedom: 3, wisdom: 1 } },
    ],
  },
  {
    id: "q33",
    text: "你更希望自己成为？",
    options: [
      { key: "A", text: "被人信任的人", weights: { loyalty: 3, righteousness: 1 } },
      { key: "B", text: "被人敬畏的人", weights: { courage: 3, charisma: 1 } },
      { key: "C", text: "被人理解的人", weights: { loyalty: 2, freedom: 2 } },
      { key: "D", text: "被人需要的人", weights: { loyalty: 2, charisma: 2 } },
    ],
  },
  {
    id: "q34",
    text: "如果你没有正式权力，你会如何影响局面？",
    options: [
      { key: "A", text: "靠专业能力让别人信服", weights: { wisdom: 3, loyalty: 1 } },
      { key: "B", text: "靠行动力先做出成果", weights: { courage: 3, charisma: 1 } },
      { key: "C", text: "靠关系和沟通形成联盟", weights: { charisma: 3, loyalty: 1 } },
      { key: "D", text: "靠信息差找到关键支点", weights: { wisdom: 3, freedom: 1 } },
    ],
  },
  {
    id: "q35",
    text: "路遇不平之事，你会？",
    options: [
      { key: "A", text: "立刻出手相助", weights: { courage: 4, righteousness: 3 } },
      { key: "B", text: "先了解清楚情况再决定", weights: { wisdom: 3, freedom: 1 } },
      { key: "C", text: "看看有没有其他人先出手", weights: { wisdom: 1, courage: -2 } },
      { key: "D", text: "用自己的方式暗中帮忙", weights: { freedom: 2, loyalty: 1 } },
    ],
  },
  {
    id: "q36",
    text: "你如何看待招安？",
    options: [
      { key: "A", text: "可以接受，正统之路更稳", weights: { loyalty: 2, righteousness: 2 } },
      { key: "B", text: "绝不接受，自由比什么都重要", weights: { freedom: 4, courage: 1 } },
      { key: "C", text: "看条件，如果对兄弟们好就行", weights: { loyalty: 3, charisma: 1 } },
      { key: "D", text: "可以利用，但保持独立", weights: { wisdom: 2, freedom: 2 } },
    ],
  },
  {
    id: "q37",
    text: "梁山聚义，你觉得最吸引你的是？",
    options: [
      { key: "A", text: "兄弟情深，有归属感", weights: { loyalty: 3, charisma: 2 } },
      { key: "B", text: "大碗喝酒大块吃肉，痛快", weights: { freedom: 3, courage: 2 } },
      { key: "C", text: "能做一番事业", weights: { courage: 2, wisdom: 1 } },
      { key: "D", text: "远离世俗规矩，按自己的方式活", weights: { freedom: 4, courage: 1 } },
    ],
  },
  {
    id: "q38",
    text: "如果你和兄弟意见严重分歧，你会？",
    options: [
      { key: "A", text: "各走各路，但不会反目", weights: { freedom: 2, loyalty: 2 } },
      { key: "B", text: "忍让一步，维护兄弟情分", weights: { loyalty: 4, charisma: 1 } },
      { key: "C", text: "据理力争，对事不对人", weights: { righteousness: 3, courage: 1 } },
      { key: "D", text: "找折中方案，避免决裂", weights: { charisma: 2, wisdom: 1 } },
    ],
  },
  {
    id: "q39",
    text: "你更欣赏哪种江湖人物？",
    options: [
      { key: "A", text: "义薄云天、说到做到的人", weights: { loyalty: 3, righteousness: 2 } },
      { key: "B", text: "足智多谋、运筹帷幄的人", weights: { wisdom: 4, freedom: 1 } },
      { key: "C", text: "豪放不羁、不拘小节的人", weights: { freedom: 3, courage: 2 } },
      { key: "D", text: "心狠手辣、不择手段的人", weights: { courage: 2, freedom: 2 } },
    ],
  },
  {
    id: "q40",
    text: "如果给你一个水浒身份，你最想成为？",
    options: [
      { key: "A", text: "聚义堂上的首领", weights: { charisma: 3, loyalty: 2 } },
      { key: "B", text: "幕后的军师", weights: { wisdom: 4, freedom: 1 } },
      { key: "C", text: "冲锋陷阵的猛将", weights: { courage: 4, freedom: 1 } },
      { key: "D", text: "行走江湖的浪子", weights: { freedom: 4, courage: 1 } },
    ],
  },
];

if (typeof window !== "undefined") {
  window.SHUIHU_DATA = { DIMENSIONS, CHARACTERS, QUESTIONS };
}

if (typeof module !== "undefined") {
  module.exports = { DIMENSIONS, CHARACTERS, QUESTIONS };
}
